id: A951899B6
title: Training in the Pure Realms of the Three Kāyas
type: translation
pechas:
- I732324E1
- I4FFA2B7E
- I204B3595
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:56.178708
  last_modified_at: 2023-01-04 12:41:56.178728
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I732324E1/8019: 567F
  I4FFA2B7E/0111: 567F
  I204B3595/8DB7: 567F
